const data = [
    {
      id: 1,
      name: "Grilled skewers",
      type: "Spicy mutton",
      price: "36.00",
      isFavourite: true,
      isLast: false,
      isBooked: true,
      img: require('../assets/images/restaurant/restaurante04.jpg'),
      image1: require("../assets/images/restaurant/restaurante04.jpg"),
      image2: require("../assets/images/restaurant/restaurante04.jpg"),
      image3: require("../assets/images/restaurant/restaurante04.jpg"),
      address: "123 Main St, Cityville",
    reviews: [
      { user: "John Doe", rating: 4, comment: "Great food!" },
      { user: "Jane Smith", rating: 5, comment: "Amazing place!" },
    ],
    description: "A fantastic restaurant serving delicious grilled skewers.",
    latitude: -8.8368200,
    longitude: 13.2343200,
      pratos: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheesy garlic pizza',
          price: 13,
          image: require("../assets/images/food/plate-1.png"),
        },
        {
          id: 2,
          name: 'Hamburguer',
          description: 'Cheesy garlic pizza',
          price: 11,
          image: require("../assets/images/food/plate-1.png"),
        },
        {
          id: 3,
          name: 'Fahita',
          description: 'Cheesy garlic pizza',
          price: 10,
          image: require("../assets/images/food/plate-1.png"),
        },
      ]
    },
    {
      id: 2,
      name: "Grilled skewers",
      type: "Spicy mutton",
      price: "45.99",
      isFavourite: false,
      isLast: false,
      isBooked: false,
      img: require('../assets/images/restaurant/restaurante02.jpg'),
      image1: require("../assets/images/restaurant/restaurante04.jpg"),
      image2: require("../assets/images/restaurant/restaurante04.jpg"),
      image3: require("../assets/images/restaurant/restaurante04.jpg"),
      address: "123 Main St, Cityville",
    reviews: [
      { user: "John Doe", rating: 4, comment: "Great food!" },
      { user: "Jane Smith", rating: 5, comment: "Amazing place!" },
    ],
    description: "A fantastic restaurant serving delicious grilled skewers.",
    latitude: 123.456,
    longitude: -78.910,
      pratos: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheesy garlic pizza',
          price: 13,
          image: require("../assets/images/food/plate-1.png"),
        },
        {
          id: 2,
          name: 'Hamburguer',
          description: 'Cheesy garlic pizza',
          price: 11,
          image: require("../assets/images/food/plate-1.png"),
        },
        {
          id: 3,
          name: 'Fahita',
          description: 'Cheesy garlic pizza',
          price: 10,
          image: require("../assets/images/food/plate-1.png"),
        },
      ]
    },
    {
        id: 3,
      name: "Grilled skewers",
      type: "Spicy mutton",
      price: "45.99",
      isFavourite: false,
      isLast: false,
      isBooked: false,
      img: require('../assets/images/restaurant/restaurante03.jpg'),
      image1: require("../assets/images/restaurant/restaurante04.jpg"),
      image2: require("../assets/images/restaurant/restaurante04.jpg"),
      image3: require("../assets/images/restaurant/restaurante04.jpg"),
      address: "123 Main St, Cityville",
    reviews: [
      { user: "John Doe", rating: 4, comment: "Great food!" },
      { user: "Jane Smith", rating: 5, comment: "Amazing place!" },
    ],
    description: "A fantastic restaurant serving delicious grilled skewers.",
    latitude: 123.456,
    longitude: -78.910,
      pratos: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheesy garlic pizza',
          price: 13,
          image: require("../assets/images/food/plate-1.png"),
        },
        {
          id: 2,
          name: 'Hamburguer',
          description: 'Cheesy garlic pizza',
          price: 11,
          image: require("../assets/images/food/plate-1.png"),
        },
        {
          id: 3,
          name: 'Fahita',
          description: 'Cheesy garlic pizza',
          price: 10,
          image: require("../assets/images/food/plate-1.png"),
        },
      ]
    },
    {
        id: 4,
      name: "Grilled skewers",
      type: "Spicy mutton",
      price: "45.99",
      isFavourite: false,
      isBooked: false,
      isLast: true,
      img: require('../assets/images/restaurant/restaurante04.jpg'),
      image1: require("../assets/images/restaurant/restaurante04.jpg"),
      image2: require("../assets/images/restaurant/restaurante04.jpg"),
      image3: require("../assets/images/restaurant/restaurante04.jpg"),
      address: "123 Main St, Cityville",
    reviews: [
      { user: "John Doe", rating: 4, comment: "Great food!" },
      { user: "Jane Smith", rating: 5, comment: "Amazing place!" },
    ],
    description: "A fantastic restaurant serving delicious grilled skewers.",
    latitude: 123.456,
    longitude: -78.910,
      pratos: [
        {
          id: 1,
          name: 'Pizza',
          description: 'Cheesy garlic pizza',
          price: 13,
          image: require("../assets/images/food/plate-1.png"),
        },
        {
          id: 2,
          name: 'Hamburguer',
          description: 'Cheesy garlic pizza',
          price: 11,
          image: require("../assets/images/food/plate-1.png"),
        },
        {
          id: 3,
          name: 'Fahita',
          description: 'Cheesy garlic pizza',
          price: 10,
          image: require("../assets/images/food/plate-1.png"),
        },
      ]
    },
  ];
  
  export default data;
  